# Generated by Django 5.2 on 2025-05-05 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('official_name', models.CharField(blank=True, max_length=255, null=True)),
                ('capital', models.CharField(blank=True, max_length=255, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('subregion', models.CharField(blank=True, max_length=100, null=True)),
                ('population', models.BigIntegerField(blank=True, null=True)),
                ('area', models.FloatField(blank=True, null=True)),
                ('flag_url', models.URLField(blank=True, null=True)),
                ('independent', models.BooleanField(null=True)),
                ('cca2', models.CharField(blank=True, max_length=5, null=True)),
                ('cca3', models.CharField(blank=True, max_length=5, null=True)),
                ('currencies', models.JSONField(blank=True, null=True)),
                ('languages', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
