# Generated by Django 5.2 on 2025-05-05 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='ccn3',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
